services:
  postgres:
    image: postgres:16
    container_name: ecom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecom_user
      POSTGRES_PASSWORD: ecom_pass
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../sql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecom_user -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - cdc_net

  zookeeper:
    image: debezium/zookeeper:2.5
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - cdc_net

  kafka:
    image: debezium/kafka:2.5
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - cdc_net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - cdc_net

  connect:
    image: debezium/connect:2.5
    container_name: connect
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: ecom_connect_cluster
      CONFIG_STORAGE_TOPIC: ecom_connect_configs
      OFFSET_STORAGE_TOPIC: ecom_connect_offsets
      STATUS_STORAGE_TOPIC: ecom_connect_status
    networks:
      - cdc_net

volumes:
  pg_data:
  minio_data:

networks:
  cdc_net:
    driver: bridge